<?php

namespace Asaas\Utils\Enums;

class PaymentsWebhookEvents
{
    public const PAYMENT_CREATED = 'PAYMENT_CREATED';

    public const PAYMENT_AWAITING_RISK_ANALYSIS = 'PAYMENT_AWAITING_RISK_ANALYSIS';

    public const PAYMENT_APPROVED_BY_RISK_ANALYSIS = 'PAYMENT_APPROVED_BY_RISK_ANALYSIS';

    public const PAYMENT_REPROVED_BY_RISK_ANALYSIS = 'PAYMENT_REPROVED_BY_RISK_ANALYSIS';

    public const PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED';

    public const PAYMENT_UPDATED = 'PAYMENT_UPDATED';

    public const PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED';

    public const PAYMENT_RECEIVED = 'PAYMENT_RECEIVED';

    public const PAYMENT_CREDIT_CARD_CAPTURE_REFUSED = 'PAYMENT_CREDIT_CARD_CAPTURE_REFUSED';

    public const PAYMENT_ANTICIPATED = 'PAYMENT_ANTICIPATED';

    public const PAYMENT_OVERDUE = 'PAYMENT_OVERDUE';

    public const PAYMENT_DELETED = 'PAYMENT_DELETED';

    public const PAYMENT_RESTORED = 'PAYMENT_RESTORED';

    public const PAYMENT_REFUNDED = 'PAYMENT_REFUNDED';

    public const PAYMENT_PARTIALLY_REFUNDED = 'PAYMENT_PARTIALLY_REFUNDED';

    public const PAYMENT_REFUND_IN_PROGRESS = 'PAYMENT_REFUND_IN_PROGRESS';

    public const PAYMENT_RECEIVED_IN_CASH_UNDONE = 'PAYMENT_RECEIVED_IN_CASH_UNDONE';

    public const PAYMENT_CHARGEBACK_REQUESTED = 'PAYMENT_CHARGEBACK_REQUESTED';

    public const PAYMENT_CHARGEBACK_DISPUTE = 'PAYMENT_CHARGEBACK_DISPUTE';

    public const PAYMENT_AWAITING_CHARGEBACK_REVERSAL = 'PAYMENT_AWAITING_CHARGEBACK_REVERSAL';

    public const PAYMENT_DUNNING_RECEIVED = 'PAYMENT_DUNNING_RECEIVED';

    public const PAYMENT_DUNNING_REQUESTED = 'PAYMENT_DUNNING_REQUESTED';

    public const PAYMENT_BANK_SLIP_VIEWED = 'PAYMENT_BANK_SLIP_VIEWED';

    public const PAYMENT_CHECKOUT_VIEWED = 'PAYMENT_CHECKOUT_VIEWED';

    public const PAYMENT_SPLIT_CANCELLED = 'PAYMENT_SPLIT_CANCELLED';

    public const PAYMENT_SPLIT_DIVERGENCE_BLOCK = 'PAYMENT_SPLIT_DIVERGENCE_BLOCK';

    public const PAYMENT_SPLIT_DIVERGENCE_BLOCK_FINISHED = 'PAYMENT_SPLIT_DIVERGENCE_BLOCK_FINISHED';
}
