<?php

namespace Asaas\Utils\Enums;

class ReceivableAnticipationWebhookEvents
{
    public const RECEIVABLE_ANTICIPATION_CANCELLED = 'RECEIVABLE_ANTICIPATION_CANCELLED';
    public const RECEIVABLE_ANTICIPATION_SCHEDULED = 'RECEIVABLE_ANTICIPATION_SCHEDULED';
    public const RECEIVABLE_ANTICIPATION_PENDING = 'RECEIVABLE_ANTICIPATION_PENDING';
    public const RECEIVABLE_ANTICIPATION_CREDITED = 'RECEIVABLE_ANTICIPATION_CREDITED';
    public const RECEIVABLE_ANTICIPATION_DEBITED = 'RECEIVABLE_ANTICIPATION_DEBITED';
    public const RECEIVABLE_ANTICIPATION_DENIED = 'RECEIVABLE_ANTICIPATION_DENIED';
    public const RECEIVABLE_ANTICIPATION_OVERDUE = 'RECEIVABLE_ANTICIPATION_OVERDUE';
}
