<?php

namespace Asaas\Utils\Enums;

class SubscriptionsWebhookEvents
{
    public const SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED';
    public const SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED';
    public const SUBSCRIPTION_INACTIVATED = 'SUBSCRIPTION_INACTIVATED';
    public const SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED';
    public const SUBSCRIPTION_SPLIT_DIVERGENCE_BLOCK = 'SUBSCRIPTION_SPLIT_DIVERGENCE_BLOCK';
    public const SUBSCRIPTION_SPLIT_DIVERGENCE_BLOCK_FINISHED = 'SUBSCRIPTION_SPLIT_DIVERGENCE_BLOCK_FINISHED';
}
